// <auto-generated />
using System;
using CrmBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrmBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418062938_AddAllWorkscopeEntities")]
    partial class AddAllWorkscopeEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrmBackend.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("BuildingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingFloor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingLatitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingLongitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuildingMakaniMap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("BuildingReconstruction")
                        .HasColumnType("boolean");

                    b.Property<string>("BuildingTypeOfUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<Guid?>("CommentAddedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CommentAddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommentDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CommentNextFollowup")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InquiryId")
                        .HasColumnType("integer");

                    b.Property<int?>("InquiryStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("InquiryWorkscopeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsFollowedUpRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CommentId");

                    b.HasIndex("CommentAddedBy");

                    b.HasIndex("InquiryId");

                    b.HasIndex("InquiryWorkscopeId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("CustomerAssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CustomerAssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerAssignedTo")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerCity")
                        .HasColumnType("text");

                    b.Property<string>("CustomerContact")
                        .HasColumnType("text");

                    b.Property<string>("CustomerCountry")
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerNationality")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CustomerNextMeetingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("text");

                    b.Property<int?>("CustomerTimeSpent")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerWhatsapp")
                        .HasColumnType("text");

                    b.Property<Guid?>("EscalatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EscalatedOn")
                        .HasColumnType("text");

                    b.Property<Guid?>("EscalationRequestedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("EscalationRequestedOn")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsEscalationRequested")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsVisitedShowroom")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WayOfContact")
                        .HasColumnType("integer");

                    b.HasKey("CustomerId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerAssignedBy");

                    b.HasIndex("CustomerAssignedTo");

                    b.HasIndex("EscalatedBy");

                    b.HasIndex("EscalationRequestedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.CustomerBranch", b =>
                {
                    b.Property<int>("CustomerBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerBranchId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerBranchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerBranch");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.CustomerComment", b =>
                {
                    b.Property<int>("CustomerCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerCommentId"));

                    b.Property<Guid>("CommentAddedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CommentAddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerCommentDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerCommentId");

                    b.HasIndex("CommentAddedBy");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerComments");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Inquiry", b =>
                {
                    b.Property<int>("InquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InquiryId"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EscalationRequestedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EscalationRequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExistingInquiryId")
                        .HasColumnType("integer");

                    b.Property<string>("InquiryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InquiryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InquiryDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InquiryEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InquiryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InquiryStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDesignProvidedByCustomer")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsEscalationRequested")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsExistingInquiry")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInquiryLocked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMeasurementProvidedByCustomer")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQuotationReschedule")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("MeasurementFees")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("QuotationAddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuotationAssignTo")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("QuotationScheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TempContractAssignedTo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("InquiryId");

                    b.HasIndex("BranchId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EscalationRequestedBy");

                    b.HasIndex("ExistingInquiryId");

                    b.HasIndex("ManagedBy");

                    b.HasIndex("QuotationAssignTo");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.InquiryWorkscope", b =>
                {
                    b.Property<int>("InquiryWorkscopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InquiryWorkscopeId"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DesignAddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DesignAssignedTo")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DesignScheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FeedbackReaction")
                        .HasColumnType("integer");

                    b.Property<int>("InquiryId")
                        .HasColumnType("integer");

                    b.Property<int?>("InquiryStatus")
                        .HasColumnType("integer");

                    b.Property<string>("InquiryWorkscopeDetailName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDesignApproved")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDesignReschedule")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDesignSentToCustomer")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMeasurementDrawing")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsMeasurementReschedule")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("MeasurementAddedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MeasurementAssignedTo")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("MeasurementScheduleDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkScopeId")
                        .HasColumnType("integer");

                    b.HasKey("InquiryWorkscopeId");

                    b.HasIndex("DesignAssignedTo");

                    b.HasIndex("InquiryId");

                    b.HasIndex("MeasurementAssignedTo");

                    b.HasIndex("WorkScopeId");

                    b.ToTable("InquiryWorkscopes");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.RoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.WorkscopeQuotationDetail", b =>
                {
                    b.Property<int>("WorkscopeQuotationDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkscopeQuotationDetailId"));

                    b.Property<string>("AccessoriesAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppliancesAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CounterTopAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InquiryWorkscopeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsUrlGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("LightningAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("QuotationAddedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("QuotationAddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("QuotationUpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("QuotationUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialItemAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TotalAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UrlGeneratedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WoodenWorkAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkscopeQuotationPic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkscopeQuotationDetailId");

                    b.HasIndex("InquiryWorkscopeId")
                        .IsUnique();

                    b.ToTable("WorkscopeQuotationDetails");
                });

            modelBuilder.Entity("WorkScope", b =>
                {
                    b.Property<int>("WorkScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkScopeId"));

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("QuestionaireType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkScopeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkScopeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkScopeId");

                    b.ToTable("WorkScopes");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Comment", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.User", "CommentAddedByUser")
                        .WithMany()
                        .HasForeignKey("CommentAddedBy");

                    b.HasOne("CrmBackend.Domain.Entities.Inquiry", "Inquiry")
                        .WithMany()
                        .HasForeignKey("InquiryId");

                    b.HasOne("CrmBackend.Domain.Entities.InquiryWorkscope", "InquiryWorkscope")
                        .WithMany("Comments")
                        .HasForeignKey("InquiryWorkscopeId");

                    b.Navigation("CommentAddedByUser");

                    b.Navigation("Inquiry");

                    b.Navigation("InquiryWorkscope");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Customer", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.Branch", "Branch")
                        .WithMany("Customers")
                        .HasForeignKey("BranchId");

                    b.HasOne("CrmBackend.Domain.Entities.User", "CustomerAssignedByUser")
                        .WithMany()
                        .HasForeignKey("CustomerAssignedBy");

                    b.HasOne("CrmBackend.Domain.Entities.User", "CustomerAssignedToUser")
                        .WithMany()
                        .HasForeignKey("CustomerAssignedTo");

                    b.HasOne("CrmBackend.Domain.Entities.User", "EscalatedByUser")
                        .WithMany()
                        .HasForeignKey("EscalatedBy");

                    b.HasOne("CrmBackend.Domain.Entities.User", "EscalationRequestedByUser")
                        .WithMany()
                        .HasForeignKey("EscalationRequestedBy");

                    b.HasOne("CrmBackend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Branch");

                    b.Navigation("CustomerAssignedByUser");

                    b.Navigation("CustomerAssignedToUser");

                    b.Navigation("EscalatedByUser");

                    b.Navigation("EscalationRequestedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.CustomerBranch", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmBackend.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerBranches")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.CustomerComment", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.User", "CommentAddedByNavigation")
                        .WithMany()
                        .HasForeignKey("CommentAddedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmBackend.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerComments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentAddedByNavigation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Inquiry", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CrmBackend.Domain.Entities.Building", "Building")
                        .WithMany("Inquiries")
                        .HasForeignKey("BuildingId");

                    b.HasOne("CrmBackend.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("CrmBackend.Domain.Entities.User", "EscalationRequestedByUser")
                        .WithMany()
                        .HasForeignKey("EscalationRequestedBy");

                    b.HasOne("CrmBackend.Domain.Entities.Inquiry", "ExistingInquiry")
                        .WithMany()
                        .HasForeignKey("ExistingInquiryId");

                    b.HasOne("CrmBackend.Domain.Entities.User", "ManagedByUser")
                        .WithMany()
                        .HasForeignKey("ManagedBy");

                    b.HasOne("CrmBackend.Domain.Entities.User", "QuotationAssignedUser")
                        .WithMany()
                        .HasForeignKey("QuotationAssignTo");

                    b.Navigation("Branch");

                    b.Navigation("Building");

                    b.Navigation("Customer");

                    b.Navigation("EscalationRequestedByUser");

                    b.Navigation("ExistingInquiry");

                    b.Navigation("ManagedByUser");

                    b.Navigation("QuotationAssignedUser");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.InquiryWorkscope", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.User", "DesignAssignedUser")
                        .WithMany()
                        .HasForeignKey("DesignAssignedTo");

                    b.HasOne("CrmBackend.Domain.Entities.Inquiry", "Inquiry")
                        .WithMany()
                        .HasForeignKey("InquiryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmBackend.Domain.Entities.User", "MeasurementAssignedUser")
                        .WithMany()
                        .HasForeignKey("MeasurementAssignedTo");

                    b.HasOne("WorkScope", "WorkScope")
                        .WithMany("InquiryWorkscopes")
                        .HasForeignKey("WorkScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignAssignedUser");

                    b.Navigation("Inquiry");

                    b.Navigation("MeasurementAssignedUser");

                    b.Navigation("WorkScope");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.RoleClaim", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.Role", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.User", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrmBackend.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.UserClaim", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.WorkscopeQuotationDetail", b =>
                {
                    b.HasOne("CrmBackend.Domain.Entities.InquiryWorkscope", "InquiryWorkscope")
                        .WithOne("QuotationDetail")
                        .HasForeignKey("CrmBackend.Domain.Entities.WorkscopeQuotationDetail", "InquiryWorkscopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InquiryWorkscope");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Building", b =>
                {
                    b.Navigation("Inquiries");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerBranches");

                    b.Navigation("CustomerComments");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.InquiryWorkscope", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("QuotationDetail")
                        .IsRequired();
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CrmBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("WorkScope", b =>
                {
                    b.Navigation("InquiryWorkscopes");
                });
#pragma warning restore 612, 618
        }
    }
}
